# This is a basic workflow to help you get started with Actions

name: AZ_Bicep

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

            - name: Azure Login
              uses: Azure/login@v1.5.1
              with:
                # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
                creds: ${{secrets.AZURE_SPN_CREDENTIAL}}


                
                # # ClientId of the Azure Service principal created.
                # client-id: # optional
                # # TenantId of the Azure Service principal created.
                # tenant-id: # optional
                # # Azure subscriptionId
                # subscription-id: # optional
                # # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
                # enable-AzPSSession: # optional
                # # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
                # environment: # optional, default is azurecloud
                # # Set this value to true to enable support for accessing tenants without subscriptions
                # allow-no-subscriptions: # optional
                # # Provide audience field for access-token. Default value is api://AzureADTokenExchange
                # audience: # optional, default is api://AzureADTokenExchange
                # # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
                # auth-type: # optional, default is SERVICE_PRINCIPAL
          
          

          
